version: '3'
services:
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    container_name: frontend
    environment:
      PORT: 3000
    ports:
      - 3000:3000
    networks:
      - weather-network
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
    environment:
      PORT: 5000
      WEATHER_API_KEY: <API-KEY>
    ports:
      - 5000:5000
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge